name: flutter_map
description: A Dart implementation of Leaflet for Flutter apps
version: 0.12.0
repository: https://github.com/johnpryan/flutter_map

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  tuple: any
  latlong2: any
  positioned_tap_detector_2: any
  transparent_image: any
  async: any
  flutter_image: any
  vector_math: any
  proj4dart: any
  meta: any
  collection: any

dev_dependencies:
  pedantic: any
  location: any
  flutter_test:
    sdk: flutter
  test: any
  mockito: any
